# Generated by Django 5.2.4 on 2025-11-24 13:37

import django.core.validators
import django.db.models.deletion
import newsletters.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(choices=[('NORMAL', 'Normal News'), ('SLIDER', 'Slider News'), ('ACHIEVEMENT', 'Employee Achievement')], db_index=True, default='NORMAL', help_text='Type of newsletter: NORMAL, SLIDER, or ACHIEVEMENT', max_length=20)),
                ('title', newsletters.models.EncryptedCharField(help_text='Encrypted newsletter title', max_length=500)),
                ('title_hash', models.CharField(db_index=True, help_text='SHA-256 hash of title for searchability (Oracle-compatible)', max_length=64)),
                ('details', newsletters.models.EncryptedTextField(help_text='Encrypted newsletter full details/body content')),
                ('details_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of details for search/filtering', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp (UAE timezone)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UAE timezone)')),
                ('author', models.ForeignKey(help_text='Newsletter creator (PROTECT prevents deletion if newsletters exist)', on_delete=django.db.models.deletion.PROTECT, related_name='newsletters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.BinaryField(help_text='Optimized full image (JPEG, max 1920px width, quality 75%, max 10MB)')),
                ('thumbnail_data', models.BinaryField(blank=True, help_text='Thumbnail (300x300px, JPEG quality 60%, max 500KB)', null=True)),
                ('original_filename', models.CharField(help_text='Sanitized original filename (stored for display)', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes (for quota tracking)', validators=[django.core.validators.MinValueValidator(0)])),
                ('mime_type', models.CharField(default='image/jpeg', help_text='MIME type: image/jpeg, image/png, image/webp', max_length=100)),
                ('is_main', models.BooleanField(db_index=True, default=False, help_text='Main/cover image flag (only one per newsletter)')),
                ('display_order', models.IntegerField(db_index=True, default=0, help_text='Order of images in gallery (0-based, main image = 0)', validators=[django.core.validators.MinValueValidator(0)])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp (UAE timezone)')),
                ('newsletter', models.ForeignKey(help_text='Parent newsletter (CASCADE deletes images when newsletter deleted)', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='newsletters.newsletter')),
            ],
            options={
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['news_type', '-created_at'], name='newsletters_news_ty_e9a2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['author', '-created_at'], name='newsletters_author__89cba5_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletterimage',
            index=models.Index(fields=['newsletter', 'display_order'], name='newsletters_newslet_2196c6_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletterimage',
            index=models.Index(fields=['newsletter', 'is_main'], name='newsletters_newslet_130c7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='newsletterimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('newsletter', 'is_main'), name='unique_main_image_per_newsletter'),
        ),
    ]
