# Generated by Django 5.2.4 on 2025-11-24 17:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='newsletter',
            name='newsletters_news_ty_e9a2d9_idx',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='position',
            field=models.IntegerField(db_index=True, default=0, help_text='Display order position (0-based, lower values appear first)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['news_type', 'position', '-created_at'], name='newsletters_news_ty_41c909_idx'),
        ),
    ]
