# Generated by Django 5.2.4 on 2025-11-12 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group')], db_index=True, max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat/avatars/')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internal_chat_thread',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('has_attachments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='internal_chat.message')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='internal_chat.thread')),
            ],
            options={
                'db_table': 'internal_chat_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posting_mode', models.CharField(choices=[('all', 'All Members'), ('admins_only', 'Admins Only')], default='all', max_length=15)),
                ('mentions_enabled', models.BooleanField(default=True)),
                ('reactions_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_settings', to='internal_chat.thread')),
            ],
            options={
                'verbose_name_plural': 'Group Settings',
                'db_table': 'internal_chat_group_settings',
            },
        ),
        migrations.CreateModel(
            name='DirectThreadKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_low_id', models.IntegerField(db_index=True)),
                ('user_high_id', models.IntegerField(db_index=True)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direct_key', to='internal_chat.thread')),
            ],
            options={
                'db_table': 'internal_chat_direct_thread_key',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('role_changed', 'Role Changed'), ('settings_changed', 'Settings Changed'), ('thread_created', 'Thread Created'), ('thread_deleted', 'Thread Deleted'), ('message_deleted', 'Message Deleted')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_audit_targets', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='internal_chat.thread')),
            ],
            options={
                'db_table': 'internal_chat_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], db_index=True, default='member', max_length=10)),
                ('is_muted', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='internal_chat.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internal_chat_participant',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='chat/attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='internal_chat.message')),
            ],
            options={
                'db_table': 'internal_chat_attachment',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'created_at'], name='internal_ch_message_3efd3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='internal_chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internal_chat_reaction',
                'indexes': [models.Index(fields=['message', 'emoji'], name='internal_ch_message_42799e_idx')],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['type', 'created_at'], name='internal_ch_type_ac315e_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['created_by', 'created_at'], name='internal_ch_created_de2285_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='internal_ch_thread__16db56_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='internal_ch_sender__6fad06_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'deleted_at', 'created_at'], name='internal_ch_thread__d33c75_idx'),
        ),
        migrations.AddIndex(
            model_name='directthreadkey',
            index=models.Index(fields=['user_low_id', 'user_high_id'], name='internal_ch_user_lo_58160c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directthreadkey',
            unique_together={('user_low_id', 'user_high_id')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['thread', 'created_at'], name='internal_ch_thread__30ca74_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='internal_ch_actor_i_ba0639_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='internal_ch_action_f7a58f_idx'),
        ),
        migrations.AddIndex(
            model_name='threadparticipant',
            index=models.Index(fields=['thread', 'user'], name='internal_ch_thread__970c49_idx'),
        ),
        migrations.AddIndex(
            model_name='threadparticipant',
            index=models.Index(fields=['user', 'joined_at'], name='internal_ch_user_id_6ca682_idx'),
        ),
        migrations.AddIndex(
            model_name='threadparticipant',
            index=models.Index(fields=['thread', 'role'], name='internal_ch_thread__1db795_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threadparticipant',
            unique_together={('thread', 'user')},
        ),
    ]
