# Generated by Django 5.2.4 on 2025-11-17 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_chat', '0003_alter_messagereaction_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='threadparticipant',
            name='unread_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='threadparticipant',
            index=models.Index(fields=['user', 'unread_count'], name='internal_ch_user_id_601c95_idx'),
        ),
    ]
