# Generated by Django 5.2.4 on 2025-11-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_chat', '0005_allow_null_message_in_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
