# Generated by Django 5.2.4 on 2025-11-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_chat', '0006_add_caption_to_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
