# Generated by Django 5.2.4 on 2025-11-26 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_chat', '0008_migrate_files_to_blobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsettings',
            name='members_can_add_others',
            field=models.BooleanField(default=False, help_text='Allow regular members to add new participants to the group'),
        ),
        migrations.AddField(
            model_name='groupsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_group_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
