# Generated by Django 5.2.4 on 2025-10-21 14:20

import django.db.models.deletion
import surveys.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_preserve_surveys_on_user_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', surveys.models.EncryptedCharField(help_text='Template name (encrypted)', max_length=200)),
                ('name_hash', models.CharField(blank=True, help_text='SHA256 hash of name for search indexing', max_length=64)),
                ('name_ar', surveys.models.EncryptedCharField(blank=True, help_text='Template name in Arabic (encrypted)', max_length=200, null=True)),
                ('description', surveys.models.EncryptedTextField(help_text='Template description (encrypted)')),
                ('description_ar', surveys.models.EncryptedTextField(blank=True, help_text='Template description in Arabic (encrypted)', null=True)),
                ('category', models.CharField(choices=[('contact', 'Contact Information'), ('event', 'Event'), ('feedback', 'Feedback'), ('registration', 'Registration'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('icon', models.CharField(default='fa-star', help_text='FontAwesome icon class', max_length=50)),
                ('preview_image', models.URLField(blank=True, help_text='Preview image URL', null=True)),
                ('is_predefined', models.BooleanField(default=False, help_text='Whether this is a system predefined template')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template (null for predefined templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Template',
                'verbose_name_plural': 'Survey Templates',
                'db_table': 'surveys_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', surveys.models.EncryptedTextField(help_text='Question text (encrypted)')),
                ('text_ar', surveys.models.EncryptedTextField(blank=True, help_text='Question text in Arabic (encrypted)', null=True)),
                ('question_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('rating', 'Rating'), ('yes_no', 'Yes/No')], default='text', max_length=50)),
                ('options', models.JSONField(blank=True, help_text='Options for choice questions (stored as JSON)', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('placeholder', surveys.models.EncryptedCharField(blank=True, help_text='Placeholder text (encrypted)', max_length=200, null=True)),
                ('placeholder_ar', surveys.models.EncryptedCharField(blank=True, help_text='Placeholder text in Arabic (encrypted)', max_length=200, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveytemplate')),
            ],
            options={
                'verbose_name': 'Template Question',
                'verbose_name_plural': 'Template Questions',
                'db_table': 'surveys_template_question',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='surveytemplate',
            index=models.Index(fields=['name_hash'], name='surveys_tmpl_name_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='surveytemplate',
            index=models.Index(fields=['category'], name='surveys_tmpl_category_idx'),
        ),
        migrations.AddIndex(
            model_name='surveytemplate',
            index=models.Index(fields=['is_predefined'], name='surveys_tmpl_predef_idx'),
        ),
        migrations.AddIndex(
            model_name='templatequestion',
            index=models.Index(fields=['template', 'order'], name='surveys_tmpl_q_order_idx'),
        ),
    ]
