# Generated by Django 5.2.4 on 2025-10-26 12:37

from django.db import migrations


def set_default_nps_csat_flags(apps, schema_editor):
    """
    Ensure all existing Question records have NPS_Calculate and CSAT_Calculate set to False.
    This is a safety measure to prevent issues with old surveys created before this feature.
    """
    Question = apps.get_model('surveys', 'Question')
    
    # Update any questions where these fields might be NULL or not properly set
    updated_count = Question.objects.filter(
        NPS_Calculate__isnull=True
    ).update(NPS_Calculate=False)
    
    updated_count += Question.objects.filter(
        CSAT_Calculate__isnull=True
    ).update(CSAT_Calculate=False)
    
    # Also ensure all questions have these values explicitly set to False if they weren't set
    # This handles edge cases where the field exists but wasn't properly initialized
    all_questions = Question.objects.all().count()
    
    if updated_count > 0:
        print(f"✓ Set default NPS_Calculate and CSAT_Calculate flags for {updated_count} questions")
    else:
        print(f"✓ All {all_questions} questions already have NPS_Calculate and CSAT_Calculate flags properly set")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - no action needed since we're just setting defaults
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_question_csat_calculate_question_nps_calculate_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_nps_csat_flags, reverse_migration),
    ]
