# Generated by Django 5.2.4 on 2025-10-26 20:12

import surveys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_set_default_nps_csat_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatequestion',
            name='CSAT_Calculate',
            field=models.BooleanField(default=False, help_text='Default CSAT calculation flag when creating survey from template'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='NPS_Calculate',
            field=models.BooleanField(default=False, help_text='Default NPS calculation flag when creating survey from template'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='max_scale',
            field=models.IntegerField(blank=True, help_text='Maximum value for rating scale (applied when creating survey from template)', null=True),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='min_scale',
            field=models.IntegerField(blank=True, help_text='Minimum value for rating scale (applied when creating survey from template)', null=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option_text',
            field=surveys.models.EncryptedCharField(help_text='Option text (encrypted). For yes/no: "yes", "no", "نعم", "لا"', max_length=255),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='satisfaction_value',
            field=models.IntegerField(blank=True, choices=[(2, 'Satisfied'), (1, 'Neutral'), (0, 'Dissatisfied')], db_index=True, help_text='CSAT satisfaction mapping (required when question.CSAT_Calculate=True for single_choice/yes_no)', null=True),
        ),
    ]
