# Generated by Django 5.2.4 on 2025-10-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_templatequestion_csat_calculate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='validation_type',
            field=models.CharField(choices=[('none', 'No Validation'), ('email', 'Email Address'), ('phone', 'Phone Number'), ('number', 'Numeric Only'), ('url', 'URL')], default='none', help_text='Validation type for text input (auto-detected from question text or manually set)', max_length=20),
        ),
    ]
