# Generated by Django 5.2.4 on 2025-11-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_add_validation_type_to_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceresponse',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC address of the device (primary device identifier)', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='deviceresponse',
            name='device_fingerprint',
            field=models.CharField(help_text='SHA256 hash of device fingerprint (MAC Address + User-Agent + Screen Resolution + Timezone + Platform)', max_length=64),
        ),
        migrations.AddIndex(
            model_name='deviceresponse',
            index=models.Index(fields=['mac_address'], name='surveys_device_mac_idx'),
        ),
    ]
    
    # Reverse migration support
    def reverse_code(apps, schema_editor):
        """Remove mac_address field and index when rolling back"""
        pass  # Django handles this automatically with RemoveField and RemoveIndex
    
    # Add atomic=False if needed for large tables
    atomic = True
